name: CI

on:
  push:
    branches:
      - "*"

jobs:
    php82:
      name: "php 8.2"
      runs-on: ubuntu-latest
      container: "nofutur3/php-tests:8.2"
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Install dependencies
          run: composer install --no-interaction

        - name: Run static analysis
          run: vendor/bin/phpstan analyse

        - name: Run tests
          run: vendor/bin/phpunit test/

    php80:
        name: "php 8.0"
        runs-on: ubuntu-latest
        container: "nofutur3/php-tests:8.0"
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install dependencies
              run: composer install --no-interaction

            - name: Run static analysis
              run: vendor/bin/phpstan analyse

            - name: Run tests
              run: vendor/bin/phpunit test/

    php81:
      name: "php 8.1"
      runs-on: ubuntu-latest
      container: "nofutur3/php-tests:8.1"
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Install dependencies
          run: composer install --no-interaction

        - name: Chesk code style
          run: vendor/bin/php-cs-fixer fix --dry-run --no-interaction

        - name: Run static analysis
          run: vendor/bin/phpstan analyse

        - name: Run tests
          run: vendor/bin/phpunit test/
